apiVersion: v1
kind: Pod
metadata:
  name: fruit-api
  namespace: default
  labels:
    app: fruit-api
spec:
  containers:
  - name: fruit-api
    image: k8smitocode/java-fruit-api:latest
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: DATABASE_HOST
      value: localhost
    - name: DATABASE_PORT
      value: "3306"
    - name: DATABASE_NAME
      value: database
    - name: DATABASE_USERNAME
      value: root
    - name: DATABASE_PASSWORD
      value: Pass123.
    ports:
    - containerPort:  8090
      name:  http     
  restartPolicy: Always