apiVersion: v1
kind: Pod
metadata:
  name: db-mysql
  namespace: default
  labels:
    app: db-mysql
spec:
  containers:
  - image: mysql
    name: db-mysql
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Pass123.
    ports:
    - containerPort:  3306
      name:  http
  restartPolicy: Always