apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: name1
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: storage
    fsType: ext4
