apiVersion: v1
kind: PersistentVolume
metadata:
  name: fruit-pv
  namespace: name1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
  