apiVersion: v1
kind: PersistentVolume
metadata:
  name: fruit-pv
  namespace: name1
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  