apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: name1
  labels:
    app: mysql
spec:
  containers:  
  - name: mysql
    image: mysql    
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Pass123.
    - name: MYSQL_DATABASE
      value: database
    ports:
    - containerPort:  3306
      name:  http
  restartPolicy: Always