apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: name1
  labels:
      app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 8080
    protocol: TCP
    nodePort: 30038