apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fruit-pvc
  namespace: name1
  labels:
    app: fruit-api
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi